import { Mulish } from 'next/font/google'
import './globals.css'
import Header from '@/component/Header'
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const mulish = Mulish({
  weight: '400',
  subsets: ['latin'],
})
 

export default function RootLayout({ children }) {
  return (
    <html lang="en" className ={mulish.className}>
      <body >
        <Header/>
        {children}
        </body>
    </html>
  )
}
